  version: "3.9"
  services:
    app:
      build:
        context: .
      ports:
        - "3000:3000"
      develop:
        watch:
          # live-sync source code into container
          - path: .
            target: /app
            action: sync
          # if dependencies change, rebuild
          - path: package.json
            action: rebuild
          - path: pnpm-lock.yaml
            action: rebuild
